// ═══════════════════════════════════════════════════════════════
// ARCHON — AI Project Templates
// ═══════════════════════════════════════════════════════════════

export const projectTemplates = {
  drone: {
    name: 'Drone Agrícola',
    type: 'drone',
    description: 'Drone quadricóptero de baixo custo para monitoramento de lavouras.',
    specs: {
      envergadura: '650mm',
      pesoMaximo: '2.5kg',
      autonomia: '25 min',
      alcance: '2km',
      cargaUtil: '500g',
    },
    components: [
      {
        id: 'frame',
        name: 'Frame Central',
        type: 'body',
        geometry: 'box',
        dimensions: { x: 0.15, y: 0.03, z: 0.15 },
        position: { x: 0, y: 0, z: 0 },
        material: 'carbon_fiber',
        color: '#1a1a2e',
        children: [
          {
            id: 'arm_fr',
            name: 'Braço Frontal Direito',
            type: 'structure',
            geometry: 'cylinder',
            dimensions: { radius: 0.01, height: 0.25 },
            position: { x: 0.12, y: 0, z: 0.12 },
            rotation: { x: 0, y: Math.PI / 4, z: Math.PI / 2 },
            material: 'carbon_fiber',
            color: '#2a2a3e',
          },
          {
            id: 'arm_fl',
            name: 'Braço Frontal Esquerdo',
            type: 'structure',
            geometry: 'cylinder',
            dimensions: { radius: 0.01, height: 0.25 },
            position: { x: -0.12, y: 0, z: 0.12 },
            rotation: { x: 0, y: -Math.PI / 4, z: Math.PI / 2 },
            material: 'carbon_fiber',
            color: '#2a2a3e',
          },
          {
            id: 'arm_br',
            name: 'Braço Traseiro Direito',
            type: 'structure',
            geometry: 'cylinder',
            dimensions: { radius: 0.01, height: 0.25 },
            position: { x: 0.12, y: 0, z: -0.12 },
            rotation: { x: 0, y: -Math.PI / 4, z: Math.PI / 2 },
            material: 'carbon_fiber',
            color: '#2a2a3e',
          },
          {
            id: 'arm_bl',
            name: 'Braço Traseiro Esquerdo',
            type: 'structure',
            geometry: 'cylinder',
            dimensions: { radius: 0.01, height: 0.25 },
            position: { x: -0.12, y: 0, z: -0.12 },
            rotation: { x: 0, y: Math.PI / 4, z: Math.PI / 2 },
            material: 'carbon_fiber',
            color: '#2a2a3e',
          },
        ],
      },
      {
        id: 'motor_fr',
        name: 'Motor Frontal Direito',
        type: 'motor',
        geometry: 'cylinder',
        dimensions: { radius: 0.015, height: 0.025 },
        position: { x: 0.22, y: 0.015, z: 0.22 },
        material: 'aluminum',
        color: '#666680',
      },
      {
        id: 'motor_fl',
        name: 'Motor Frontal Esquerdo',
        type: 'motor',
        geometry: 'cylinder',
        dimensions: { radius: 0.015, height: 0.025 },
        position: { x: -0.22, y: 0.015, z: 0.22 },
        material: 'aluminum',
        color: '#666680',
      },
      {
        id: 'motor_br',
        name: 'Motor Traseiro Direito',
        type: 'motor',
        geometry: 'cylinder',
        dimensions: { radius: 0.015, height: 0.025 },
        position: { x: 0.22, y: 0.015, z: -0.22 },
        material: 'aluminum',
        color: '#666680',
      },
      {
        id: 'motor_bl',
        name: 'Motor Traseiro Esquerdo',
        type: 'motor',
        geometry: 'cylinder',
        dimensions: { radius: 0.015, height: 0.025 },
        position: { x: -0.22, y: 0.015, z: -0.22 },
        material: 'aluminum',
        color: '#666680',
      },
      {
        id: 'prop_fr',
        name: 'Hélice FR',
        type: 'propeller',
        geometry: 'torus',
        dimensions: { radius: 0.065, tube: 0.003 },
        position: { x: 0.22, y: 0.03, z: 0.22 },
        material: 'abs_plastic',
        color: '#00d4ff40',
      },
      {
        id: 'prop_fl',
        name: 'Hélice FL',
        type: 'propeller',
        geometry: 'torus',
        dimensions: { radius: 0.065, tube: 0.003 },
        position: { x: -0.22, y: 0.03, z: 0.22 },
        material: 'abs_plastic',
        color: '#00d4ff40',
      },
      {
        id: 'prop_br',
        name: 'Hélice BR',
        type: 'propeller',
        geometry: 'torus',
        dimensions: { radius: 0.065, tube: 0.003 },
        position: { x: 0.22, y: 0.03, z: -0.22 },
        material: 'abs_plastic',
        color: '#00d4ff40',
      },
      {
        id: 'prop_bl',
        name: 'Hélice BL',
        type: 'propeller',
        geometry: 'torus',
        dimensions: { radius: 0.065, tube: 0.003 },
        position: { x: -0.22, y: 0.03, z: -0.22 },
        material: 'abs_plastic',
        color: '#00d4ff40',
      },
      {
        id: 'battery',
        name: 'Bateria LiPo',
        type: 'electronics',
        geometry: 'box',
        dimensions: { x: 0.06, y: 0.025, z: 0.035 },
        position: { x: 0, y: -0.025, z: 0 },
        material: 'abs_plastic',
        color: '#f59e0b',
      },
      {
        id: 'camera',
        name: 'Câmera RGB',
        type: 'sensor',
        geometry: 'sphere',
        dimensions: { radius: 0.015 },
        position: { x: 0, y: -0.04, z: 0.06 },
        material: 'abs_plastic',
        color: '#333344',
      },
      {
        id: 'landing_gear_l',
        name: 'Trem de Pouso Esquerdo',
        type: 'structure',
        geometry: 'cylinder',
        dimensions: { radius: 0.005, height: 0.06 },
        position: { x: -0.08, y: -0.05, z: 0 },
        material: 'carbon_fiber',
        color: '#2a2a3e',
      },
      {
        id: 'landing_gear_r',
        name: 'Trem de Pouso Direito',
        type: 'structure',
        geometry: 'cylinder',
        dimensions: { radius: 0.005, height: 0.06 },
        position: { x: 0.08, y: -0.05, z: 0 },
        material: 'carbon_fiber',
        color: '#2a2a3e',
      },
    ],
  },

  motorcycle: {
    name: 'Moto Elétrica Urbana',
    type: 'motorcycle',
    description: 'Motocicleta elétrica compacta para deslocamento urbano sustentável.',
    specs: {
      comprimento: '1800mm',
      velocidadeMax: '80 km/h',
      autonomia: '120 km',
      pesoTotal: '95kg',
      potencia: '5kW',
    },
    components: [
      {
        id: 'chassis',
        name: 'Chassi Tubular',
        type: 'body',
        geometry: 'box',
        dimensions: { x: 0.08, y: 0.12, z: 0.6 },
        position: { x: 0, y: 0.25, z: 0 },
        material: 'steel',
        color: '#2a2a3e',
      },
      {
        id: 'front_wheel',
        name: 'Roda Dianteira',
        type: 'wheel',
        geometry: 'torus',
        dimensions: { radius: 0.2, tube: 0.04 },
        position: { x: 0, y: 0.2, z: 0.4 },
        rotation: { x: Math.PI / 2, y: 0, z: 0 },
        material: 'rubber',
        color: '#1a1a1a',
      },
      {
        id: 'rear_wheel',
        name: 'Roda Traseira',
        type: 'wheel',
        geometry: 'torus',
        dimensions: { radius: 0.2, tube: 0.04 },
        position: { x: 0, y: 0.2, z: -0.4 },
        rotation: { x: Math.PI / 2, y: 0, z: 0 },
        material: 'rubber',
        color: '#1a1a1a',
      },
      {
        id: 'seat',
        name: 'Assento',
        type: 'comfort',
        geometry: 'box',
        dimensions: { x: 0.15, y: 0.05, z: 0.3 },
        position: { x: 0, y: 0.4, z: -0.1 },
        material: 'abs_plastic',
        color: '#1a1a2e',
      },
      {
        id: 'battery_pack',
        name: 'Pack de Baterias',
        type: 'electronics',
        geometry: 'box',
        dimensions: { x: 0.12, y: 0.15, z: 0.25 },
        position: { x: 0, y: 0.15, z: 0 },
        material: 'aluminum',
        color: '#00d4ff30',
      },
      {
        id: 'motor_hub',
        name: 'Motor Hub Traseiro',
        type: 'motor',
        geometry: 'cylinder',
        dimensions: { radius: 0.08, height: 0.06 },
        position: { x: 0, y: 0.2, z: -0.4 },
        material: 'aluminum',
        color: '#666680',
      },
      {
        id: 'handlebar',
        name: 'Guidão',
        type: 'control',
        geometry: 'cylinder',
        dimensions: { radius: 0.012, height: 0.35 },
        position: { x: 0, y: 0.45, z: 0.35 },
        rotation: { x: 0, y: 0, z: Math.PI / 2 },
        material: 'aluminum',
        color: '#888899',
      },
      {
        id: 'front_fork',
        name: 'Garfo Dianteiro',
        type: 'structure',
        geometry: 'cylinder',
        dimensions: { radius: 0.015, height: 0.35 },
        position: { x: 0, y: 0.35, z: 0.38 },
        rotation: { x: 0.3, y: 0, z: 0 },
        material: 'steel',
        color: '#555566',
      },
      {
        id: 'headlight',
        name: 'Farol LED',
        type: 'electronics',
        geometry: 'sphere',
        dimensions: { radius: 0.04 },
        position: { x: 0, y: 0.38, z: 0.48 },
        material: 'glass',
        color: '#ffffcc',
      },
    ],
  },

  robot: {
    name: 'Robô Assistente Doméstico',
    type: 'robot',
    description: 'Robô autônomo para tarefas domésticas simples como organização e limpeza.',
    specs: {
      altura: '450mm',
      largura: '300mm',
      peso: '5kg',
      autonomia: '4 horas',
      sensores: 'LIDAR, câmera, ultrassom',
    },
    components: [
      {
        id: 'base',
        name: 'Base Circular',
        type: 'body',
        geometry: 'cylinder',
        dimensions: { radius: 0.15, height: 0.06 },
        position: { x: 0, y: 0.03, z: 0 },
        material: 'abs_plastic',
        color: '#1a1a2e',
      },
      {
        id: 'body_main',
        name: 'Corpo Principal',
        type: 'body',
        geometry: 'cylinder',
        dimensions: { radius: 0.12, height: 0.2 },
        position: { x: 0, y: 0.16, z: 0 },
        material: 'abs_plastic',
        color: '#22223a',
      },
      {
        id: 'head',
        name: 'Cabeça / Display',
        type: 'sensor',
        geometry: 'sphere',
        dimensions: { radius: 0.08 },
        position: { x: 0, y: 0.34, z: 0 },
        material: 'abs_plastic',
        color: '#0f0f18',
      },
      {
        id: 'eye_left',
        name: 'Câmera Esquerda',
        type: 'sensor',
        geometry: 'sphere',
        dimensions: { radius: 0.015 },
        position: { x: -0.03, y: 0.35, z: 0.07 },
        material: 'glass',
        color: '#00d4ff',
      },
      {
        id: 'eye_right',
        name: 'Câmera Direita',
        type: 'sensor',
        geometry: 'sphere',
        dimensions: { radius: 0.015 },
        position: { x: 0.03, y: 0.35, z: 0.07 },
        material: 'glass',
        color: '#00d4ff',
      },
      {
        id: 'arm_left',
        name: 'Braço Esquerdo',
        type: 'actuator',
        geometry: 'cylinder',
        dimensions: { radius: 0.015, height: 0.18 },
        position: { x: -0.15, y: 0.2, z: 0 },
        rotation: { x: 0, y: 0, z: 0.3 },
        material: 'aluminum',
        color: '#666680',
      },
      {
        id: 'arm_right',
        name: 'Braço Direito',
        type: 'actuator',
        geometry: 'cylinder',
        dimensions: { radius: 0.015, height: 0.18 },
        position: { x: 0.15, y: 0.2, z: 0 },
        rotation: { x: 0, y: 0, z: -0.3 },
        material: 'aluminum',
        color: '#666680',
      },
      {
        id: 'wheel_left',
        name: 'Roda Esquerda',
        type: 'wheel',
        geometry: 'cylinder',
        dimensions: { radius: 0.04, height: 0.02 },
        position: { x: -0.13, y: 0.04, z: 0 },
        rotation: { x: 0, y: 0, z: Math.PI / 2 },
        material: 'rubber',
        color: '#333344',
      },
      {
        id: 'wheel_right',
        name: 'Roda Direita',
        type: 'wheel',
        geometry: 'cylinder',
        dimensions: { radius: 0.04, height: 0.02 },
        position: { x: 0.13, y: 0.04, z: 0 },
        rotation: { x: 0, y: 0, z: Math.PI / 2 },
        material: 'rubber',
        color: '#333344',
      },
      {
        id: 'lidar',
        name: 'Sensor LIDAR',
        type: 'sensor',
        geometry: 'cylinder',
        dimensions: { radius: 0.03, height: 0.02 },
        position: { x: 0, y: 0.42, z: 0 },
        material: 'abs_plastic',
        color: '#a855f7',
      },
    ],
  },
};
